name: gym_presence
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.2.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  faker: ^2.1.0
  intl: ^0.19.0
  provider: ^6.1.1
  http: ^1.2.0
  firebase_core: ^2.25.5
  firebase_auth: 4.17.4
  cloud_firestore: ^4.15.5
  firebase_storage: ^11.6.6
  introduction_screen: ^3.1.12
  get: 4.6.6
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/images/splash1.png
    - assets/images/splash2.png
    - assets/images/splash3.png
  uses-material-design: true

